### ISSUE TITLE
ADDRR0 unable to bind string

### ISSUE THREAD

**Issue by socomsystems** [hexonet/ispapicli#1]
`ispapi --login=id --password=pass -e54cd --UPDATEDNSZONE DNSZONE <zone.name.> ADDRR0 host A <IP Address>`
The simple above documented syntax for ADDRR doesn't seem to work via ispapicli

Returns: 
`[RESPONSE]
code=503
description=Invalid Parameter: A
EOF
`
I've tried this in the GUI version as well and for some reason its making "A" A= within the context.  However, if you manually place ADDRR0 host A <ip address> in the context box in the GUI and execute, I get success.

**Comment by papakai** [comment]
Dear socomsystems,

thanks for getting in touch with us and your interest in this tool.
This tool is right now in development to be reviewed from scratch, so what you see here is still unstable code. When we reach a new level, we will release the first version and probably also publishing it to PyPi.

Subscribe to new releases of this repository to get informed.
I'll add a notice for others this being in `WIP` status.

If you're looking for a tool for managing DNSZone, we can point you to DNSControl. Load the last release of DNSControl v2, an update for v3 is pending.
if you have further questions, feel free to ask.
