### ISSUE TITLE
Not working: pyinstaller instructions

### ISSUE THREAD

**Issue by papakai** [hexonet/ispapicli#13]
```bash
> pyinstaller --onefile ispapi.py
39 INFO: PyInstaller: 4.2
39 INFO: Python: 3.6.9
40 INFO: Platform: Linux-5.4.0-64-generic-x86_64-with-Ubuntu-18.04-bionic
40 INFO: wrote /home/**********/git/ispapicli/ispapi.spec
42 INFO: UPX is not available.
script '/home/**********/git/ispapicli/ispapi.py' not found
```

I checked also some older releases, no `ispapi.py` found.
Still, that process was added related to Windows and MacOS and therefore maybe not working under Linux...

Please review.

**Comment by Rashad-j** [comment]
I think you missed navigating to the ispapicli.py first before running pyinstaller.

**Comment by papakai** [comment]
@Rashad-j ty, yes an oversight on my end. It is mentioned in the docs.

**Comment by papakai** [comment]
```bash
> cd hexonet/ispapicli 
> pyinstaller --onefile ispapi.py
37 INFO: PyInstaller: 4.2
37 INFO: Python: 3.6.9
37 INFO: Platform: Linux-5.4.0-65-generic-x86_64-with-Ubuntu-18.04-bionic
37 INFO: wrote /home/ad.ks.de/kschwarz/git/ispapicli/hexonet/ispapicli/ispapi.spec
39 INFO: UPX is not available.
script '/home/ad.ks.de/kschwarz/git/ispapicli/hexonet/ispapicli/ispapi.py' not found
```

**Comment by papakai** [comment]
ok I noticed now the issue in the docs. please replace:

```
pyinstaller --onefile ispapi.py
```
with
```
pyinstaller --onefile ispapicli.py
```

**Comment by Rashad-j** [comment]
That's true. Changing the tool name came later after the documentation was released. The old name followed the old tool name. Thus the documentation were not updated. I will change it accordingly. Thank you for investigating
